# Generated by Django 3.0.3 on 2020-02-28 15:25

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='uuid',
            field=models.CharField(db_index=True, default=backend.models.make_uuid, editable=False, max_length=36, unique=True),
        ),
    ]
